### ISSUE TITLE
battery saver script and dim lights?

### ISSUE THREAD

**Issue by samuaz** [rsm-gh/akbl#10]
hi i want to know if there is a script to use in combination with tlp for save battery for example to off all light except left and right zones of keyboards and turn off all others? and there is a possible to dim the light like windows in battery mode?

thanks a lot!!

**Comment by rsm-gh** [comment]
Hi, 

It actually exist on the code the support for the different modes of the computer (Normal, Stand By, AC Power, Charging, On Battery), sadly this feature of pyAlienFx didn't worked well and I disabled it from the GUI.

Another minor problem about doing this, it's that the current python bindings does not allow zone selection... BUT can do what you want yo do with some hacks. Here's what I have in mind:

1) Find some bash/python that command tells you if the computer is on the state you want.
2) Make a profile with the zones and colors that you want to use
3) Create a daemon script with the python bindings
4) Run the script when starting the session

The script will probably look like this:

```
#!/usr/bin/python3
#
 
from time import sleep
from AlienwareKBL import AlienwareKBL 
 
AKBLConnection=AlienwareKBL()
  
if not AKBLConnection.ping():
    print("The connection with the daemon is off")
    exit()

def computer_is_on_battery():
    if .. bla bla bla:
        return True
    return False

battery_state=False
normal_state=False

while True:

    if computer_is_on_battery():
        if battery_state==False:
            AKBLConnection.set_profile('OnBattery')
            battery_state=True
            normal_state=False

    elif normal_state == False:

        AKBLConnection.set_profile('Default')
        battery_state=False
        normal_state=True

     sleep(1)             
```             

Then I see two problems of this script:

1) It will be running all the time on the background, so is it really battery saving? I don't know
2) If the battery mode is not being used anymore, it will set a default profile. Maybe it would be nice adding a binding to get the current profile, like that the script could set the last profile that you've used.
