### ISSUE TITLE
headless installation

### ISSUE THREAD

**Issue by kylrth** [rsm-gh/akbl#103]
https://github.com/rsm-gh/akbl/issues/100#issuecomment-940683116

I would really appreciate having this, but I recognize it's not a normal use-case. :)

**Comment by kylrth** [comment]
Any word on this? My server lights up our house at night because I made the mistake of setting jazzy colors before blowing Windows away. :stuck_out_tongue_winking_eye:

**Comment by rsm-gh** [comment]
mmm, I may do it but first, what’s your computer model? It would be a shame to code it and then realize that akbl does not fully works on your server

**Comment by kylrth** [comment]
I'm the guy from #100 :)

**Comment by rsm-gh** [comment]
Hello @kylrth ,

I just implemented the feature, the setup script does not use the GUI anymore.

Best regards,
rsm~
