### ISSUE TITLE
Doesnt detect my laptop model (15r4) and i cant select my model in the gui for some reason

### ISSUE THREAD

**Issue by gamerjag** [rsm-gh/akbl#106]
# System information

+ Distribution name: Pop! OS 
+ Distribution version:22.04
+ Python3 version: `3.10.4'
+ akbl version: `2019.05.26`
+ Computer model: 15R4
+ Daemon status: `False`

# Bug description
Doesnt detect my laptop model (15r4) and i cant select my model in the gui for some reason
Daemon says "The computer is not supported"
when i list the usb devices there arent any alienware devices

**Comment by rsm-gh** [comment]
Hello @gamerjag ,

In order to take a look to this, I need you to post the USB data of your computer. The instructions are [here](https://github.com/rsm-gh/akbl#if-my-computer-is-not-supported-what-can-i-do).

rsm~

**Comment by rsm-gh** [comment]
> when i list the usb devices there arent any alienware devices

So there is a problem with your hardware. I can not help you if you want have an USB alienware device.
