### ISSUE TITLE
Add support to Alienware X17 R1

### ISSUE THREAD

**Issue by jj-devs** [rsm-gh/akbl#111]
Hello, thank you for this great contribution to the community.

# System information

+ Distribution name: Manjaro Linux
+ Distribution version: Ruah 21.3.7
+ Python3 version: Python 3.10.5
+ akbl version: 2019.05.26
+ Computer model: Alienware x17 R1
+ Daemon status: True

# Bug description
I try install akbl, my laptop was recognized as `15R4`, no USB detected data.
![image](https://user-images.githubusercontent.com/97807351/185042890-fc6772bf-a738-47a1-b574-16040338dba2.png)

output `lsusb -D /dev/bus/usb/003/003`

![image](https://user-images.githubusercontent.com/97807351/185044300-f12b6388-393d-40ce-ae60-a09f0849e887.png)

Even, i try use the block testing window but no success.
![image](https://user-images.githubusercontent.com/97807351/185045232-e4704112-5b22-4b4e-85e8-74fbbc2cceca.png)

**Comment by rsm-gh** [comment]
Hello @jj-devs , 

What is the problem? I see that the block testing window recognizes your computer, then when you try to set some lights on and colors what happens?

rsm~

**Comment by jj-devs** [comment]
Hello @rsm-gh 

Actually, I selected the most recent model from those available because R1 does not appear, and in this case no color of all the available LEDs changes.
If you need any screen or instructions, I can send it with pleasure, thanks

**Comment by rsm-gh** [comment]
@jj-devs But I do not understand, when you use the block testing window it says "Device found", so then you can start making tests by appliying colors etc. What happens then? Do you have a message error? A message from the block testing window?

**Comment by jj-devs** [comment]
@rsm-gh , This is what i do:
1) Download stable branch and dependencies, this is the output:
![image](https://user-images.githubusercontent.com/97807351/216209343-44249857-307b-4ee6-8fd5-c69dc37319ff.png)

2)  When i run akbl this is the output:
![image](https://user-images.githubusercontent.com/97807351/216210240-5ee182df-9e87-40be-93c4-b76224fb57ce.png)

3) When i choose the colors i save then nothing happen and keep 'Applying the configuration'
![image](https://user-images.githubusercontent.com/97807351/216210599-5180d1dc-0ccb-4124-8ab0-05e457407242.png)

4) When i choose lights on or off:
![image](https://user-images.githubusercontent.com/97807351/216211000-0980ea21-d87f-486a-a732-364de29bf874.png)

5) In the block testing i have this:
![image](https://user-images.githubusercontent.com/97807351/216211137-39fca0f6-5f7d-466e-b1be-34dc789c71e8.png)

**Comment by rsm-gh** [comment]
Ah ok, now I see. I'm sorry but I will not be able to help you.

Best Regards
