### ISSUE TITLE
Zonescan not working Alienware Auora R6 Desktop

### ISSUE THREAD

**Issue by Ocean572** [rsm-gh/akbl#113]
/!\ IF YOU WANT YOUR BUG TO BE TREATED FILL THIS TEMPLATE AND DO NOT MODIFY IT. /!\

      Also, before submitting any bug download and
            install the last version of akbl.

# System information

Alienware Aurora R6 (07DB)
product: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
          product: Xeon E3-1200 v6/7th Gen Core Processor Host Bridge/DRAM Registers
             product: 6th-10th Gen Core Processor PCIe Controller (x16)
                product: GP104 [GeForce GTX 1070]

+ Distribution name:
+ Distribution version:
+ Python3 version: `python3 --version`
+ akbl version: `akbl -v`
+ Computer model: Alienware aurora R6
+ Daemon status: `akbl --daemon-is-on`

# Bug description

I am trying to perform a zonescan and I am encountering this error. I am also unable to open the gui because if says no supported alienfx controller found.

When i type "sudo alienfx" I receive this error below...

You are running alienfx under Python-Version: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
ERROR:root:No Alien FX controller, defined by a supported model, found!
would you like to perform a zonescan? (y/n):y
Performing zonescan...
Welcome. This will help you to scan for alienfx-controllers and their lighting zones.
Traceback (most recent call last):
  File "/usr/local/bin/alienfx", line 33, in <module>
    sys.exit(load_entry_point('alienfx==2.4.0', 'console_scripts', 'alienfx')())
  File "/usr/local/lib/python3.10/dist-packages/alienfx-2.4.0-py3.10.egg/alienfx/ui/console/main.py", line 81, in start
  File "/usr/local/lib/python3.10/dist-packages/alienfx-2.4.0-py3.10.egg/alienfx/ui/console/main.py", line 64, in doZonescan
  File "/usr/local/lib/python3.10/dist-packages/alienfx-2.4.0-py3.10.egg/alienfx/core/zonescanner.py", line 134, in scan
TypeError: 'NoneType' object is not iterable

**Comment by rsm-gh** [comment]
@Ocean572 you are in the wrong github. This is not AlienFX.
