### ISSUE TITLE
No module named 'AKBL'

### ISSUE THREAD

**Issue by Webxorcist** [rsm-gh/akbl#26]
Hi,

I have an AlienWare 17" R4 with openSUSE Leap 42.2.

I followed your installations instructions and when I start alienware-kbl --on I get the following:

```
alienware-kbl --on
Traceback (most recent call last):
  File "/usr/share/AlienwareKBL/DefaultArguments.py", line 23, in <module>
    from AKBL import AKBL
ImportError: No module named 'AKBL'
```

**Comment by rsm-gh** [comment]
Are you using the stable or the new version? Also if you' re using python 3.6+ this is normal... the installation script only installs until python 3.6. You can check it at the "postinst" script.

**Comment by rsm-gh** [comment]
Fixed the Oct 29, 2017 after merging the new-version branch.

**Comment by GrimBShrout** [comment]
Having the same issue - although I'm on Fedora mainline. I can manually run some of the modules which shows me that it is working. Beginning to think the structure of the build may be the problem or having to import modules a different way.

**Comment by rsm-gh** [comment]
@GrimBShrout  I'm not having that problem. And actually, I recently made lots of code changes and modified some of the installation files so it may be possible that I brake something.

Can you post me the ouput of:
    1. The installation script
    2. The command `python`

and tell me which commands / imports are failing?

Regards,
rsm
