### ISSUE TITLE
ModuleNotFoundError: No module named 'AKBL' on Alienware 15 Manjaro Linux(Arch Based)

### ISSUE THREAD

**Issue by geekyJock8** [rsm-gh/akbl#46]
# System information

+ Distribution name: Manjaro Linux
+ Distribution version: 17.1.12
+ Python version: 3.7.0
+ Computer model: Alienware 15
+ Output of the command `alienware-kbl --daemon-is-on`: `alienware-kbl: command not found`
+ Output of the command `akbl --daemon-is-on`: 
```
Traceback (most recent call last):
  File "/usr/share/AKBL/launch/default_arguments.py", line 22, in <module>
    from AKBL.Bindings import Bindings
ModuleNotFoundError: No module named 'AKBL'
```

# Bug description
This package used to work fine but recently I upgraded my system and also upgraded this package but when I try to run this, I get this error:
```
  File "/usr/share/AKBL/launch/gui.py", line 19, in <module>
    from AKBL.ADDONS.GUI.GUI import main
ModuleNotFoundError: No module named 'AKBL'
```

**Comment by josedellabosca** [comment]
I have the same problem

**Comment by rsm-gh** [comment]
Hi @geekyJock8  and @josedellabosca,

Thanks for pointing this out ! I just pushed some commits and it should now be corrected. I'll wait your feedback to close the bug,

Regards

**Comment by josedellabosca** [comment]
It is working like charm now (console commands), i have this error when trying to open GUI 

localhost /home/jose/akbl-stable # akbl 
Traceback (most recent call last):
  File "/usr/share/AKBL/launch/gui.py", line 19, in <module>
    from AKBL.ADDONS.GUI.GUI import main
  File "/usr/lib64/python3.6/AKBL/ADDONS/GUI/GUI.py", line 21, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

**Comment by rsm-gh** [comment]
@josedellabosca I guess that your distribution is having some problem with `python-gobject`. Check if the package is installed and if you still having problem you may want to read [this](https://bbs.archlinux.org/viewtopic.php?id=204849). On Archlinux everything is working  !

**Comment by josedellabosca** [comment]
Fixed, problem was with pygobject versions, i have compiled it with the incorrect PYTHON_TARGETS variable in the make.conf

**Comment by auriberto** [comment]
I have this problem in my pop_os pc and I didn´t see how to solve it here. You guys wrote to each other in private?

**Comment by rsm-gh** [comment]
@auriberto Wich is your version of python?

**Comment by auriberto** [comment]
Hi Rafael,

My python version:

*python3 --version*Python 3.10.4

*lsusb:*Bus 002 Device 003: ID 8087:07da Intel Corp. Centrino Bluetooth
Wireless Transceiver
Bus 002 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 004: ID 064e:8127 Suyin Corp. Laptop_Integrated_Webcam_FHD
Bus 001 Device 003: ID 187c:0520 Alienware Corporation M17xR3
Bus 001 Device 002: ID 8087:0024 Intel Corp. Integrated Rate Matching Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 002: ID e2b7:0811 Jie Li CD002
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

*lsusb -D /dev/bus/usb/001/003*Device: ID 187c:0520 Alienware Corporation
M17xR3
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               1.10
  bDeviceClass            0
  bDeviceSubClass         0
  bDeviceProtocol         0
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0520
  bcdDevice            0.00
  iManufacturer           1 Alienware Gaming
  iProduct                2 M17xR3
  iSerial                 3 1.0.5
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0
    bmAttributes         0x80
      (Bus Powered)
    MaxPower               64mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0
      bInterfaceProtocol      0
      iInterface              0
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
         Report Descriptors:
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)

Thanks,

Auriberto

**Comment by rsm-gh** [comment]
@auriberto ,

I just pushed a commit to make dynamic installations on python3, if you download & install the new version you should see during the installation something like 
```
[3/5] Creating the python links...
linked python3
linked python3.10
```

and the module `AKBL` should work. 

Please keep me updated, 
rsm~

**Comment by auriberto** [comment]
It worked perfectly!

Thank you so much for your help.

Auriberto.
