### ISSUE TITLE
"Model selector feature" for computers with common vendor id and product id

### ISSUE THREAD

**Issue by rsm-gh** [rsm-gh/akbl#51]
AKBL uses the "idProduct"  to detect the computer model and apply the defined configuration. The problem is that some computer models share the same id:

```
COMPUTER                idVendor        idProduct
------------------------------------------------------------------
Aurora R4               6268            1299
M17X R1                 6268            1299

M14X R1                 6268            1313
M14X R2                 6268            1313

Alienware15 R3          6268            1328
M17X R4                 6268            1328

M17X R5                 6268            1360
Alienware15 R4          6268            1360

```

Some feature must be developed to make the user choose the right model.

**As a momentary solution, the best way of fixing this is to delete the non-used profile from the folder `/usr/share/doc/AKBL/computers/`.** This must be done every time that the software is installed.

**Comment by josedellabosca** [comment]
what if we choose the model on installation? after all it wont change

**Comment by rsm-gh** [comment]
fork [vselector](https://github.com/rsm-gh/akbl/tree/vselector)

**Comment by rsm-gh** [comment]
[#55](https://github.com/rsm-gh/akbl/pull/55) closes this.
