### ISSUE TITLE
Starting the daemon trough the terminal

### ISSUE THREAD

**Issue by rsm-gh** [rsm-gh/akbl#62]
# System information

+ Distribution name: Manjaro
+ Distribution version: 4.19.45
+ Python3 version: 3.7.3
+ akbl version: 2019.04.14
+ Computer model: AW 15R1

# Bug description

Reported by [@e-leclercq here](https://github.com/rsm-gh/akbl/issues/60#issuecomment-498537713).
 
When I attempt to start the daemon via the command ```sudo akbl --start-daemon```, the process hangs in the terminal without ending and unlike your case, no output is given (even when I stop the process). 

However, when I reboot and run akbl, without the start daemon flag, it works just fine. So I think there might be some issue starting the daemon with that command, but not necessarily the support for the 15R1.

**Comment by rsm-gh** [comment]
Hello @e-leclercq, 

I believe that you're making a wrong use of the daemon. It is normal that when using `akbl --start-daemon` the process never ends since it must be used as a background process (a daemon).

By default it is started from `systemd` and you shouldn't start it by your self.  The only reason for manually starting it is to debug akbl. And also i'd like to remark that the `systemd` daemon should be stopped to avoid having multiple instances ruining `systemctl stop akbl`.

~rsm

**Comment by e-leclercq** [comment]
Ah, my bad, I misunderstood what the command was doing. 

Thank you.
