### ISSUE TITLE
Add support to the M17X R2

### ISSUE THREAD

**Issue by aliencolors** [rsm-gh/akbl#71]
# System information
Bus 002 Device 004: ID 187c:0524 Alienware Corporation
idVendor           0x187c Alienware Corporation
Device: ID 187c:0524 Alienware Corporation
+ Distribution name: Kubuntu
+ Distribution version: 19
+ Python3 version: `python3 --version` python 3.7.3
+ akbl version: `akbl -v` 2019.05.26
+ Computer model: M17X R2
+ Daemon status: `akbl --daemon-is-on` False

**Comment by rsm-gh** [comment]
Hello @aliencolors , 

Please post your whole USB device data as indicated in the [help section](https://github.com/rsm-gh/akbl#if-my-computer-is-not-supported-what-can-i-do). Also, are you sure that your computer is an M17X R2? Because that computer is already in the configuration.

~rsm

**Comment by aliencolors** [comment]
lsusb
Bus 002 Device 004: ID 187c:0524 Alienware Corporation 
Bus 002 Device 003: ID 13d3:3411 IMC Networks 
Bus 002 Device 002: ID 8087:8000 Intel Corp. 
Bus 002 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0c45:64dd Microdia 
Bus 001 Device 002: ID 8087:8008 Intel Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

**Comment by aliencolors** [comment]
Device: ID 187c:0524 Alienware Corporation 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               0.02
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0524 
  bcdDevice            0.00
  iManufacturer           1 Alienware
  iProduct                2 M17x
  iSerial                 3 2.3.0
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10
Device Status:     0x0000
  (Bus Powered)

**Comment by aliencolors** [comment]
[Device found]: Vendor ID: 6268	 Product ID: 1316

I saw M17R1 in the list  but not M17R2.

is there anymore information you need?

**Comment by hedmo** [comment]
i like to have it to :+1:

**Comment by rsm-gh** [comment]
@aliencolors  @hedmo , Hello, sorry for taking so long. I just added your computer to the configurations and I used a M17XR1 as reference.

You can now download the stable branch and test it. Don't hesitate to tell me if you have problems or if it is necessary to correct some zones.

~rsm

**Comment by aliencolors** [comment]
Thank you, i downloaded, installed and ran the new stable. When launched the model chooser opened i saw my computer model you added but i am unable to choose it or any other of the options.

**Comment by aliencolors** [comment]
this is the error message i got when trying to --start-deamon 
ERROR from `/usr/lib/python3.7/AKBL/Engine/Controller.py` on method `__init__`:
The computer is not supported.

**Comment by rsm-gh** [comment]
@aliencolors , sorry I made a mistake when adding the configuration. You should now be able to select it !

**Comment by aliencolors** [comment]
Thank you, its working great.

**Comment by rsm-gh** [comment]
@aliencolors 

Happy to hear that !
