### ISSUE TITLE
Add Support Alienware 17 R4

### ISSUE THREAD

**Issue by spikelinux** [rsm-gh/akbl#82]
System information

    Distribution name: Debian
    Distribution version: 10
    Python3 version: 2.7.18
    akbl version: 2019.05.26
    Computer model: Alienware 17" R4
    Daemon status: False

Podrias agregar mi equipo, me esta mandado este error al levantar el demonio:

**ERROR from `/usr/lib/python3.8/AKBL/Engine/Controller.py` on method `__init__`:
The computer is not supported.**

> Device: ID 187c:0530 Alienware Corporation 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               0.02
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x187c Alienware Corporation
  idProduct          0x0530 
  bcdDevice            0.00
  iManufacturer           1 Alienware
  iProduct                2 AW1517
  iSerial                 3 02.90
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0029
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                0mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.01
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      56
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x000a  1x 10 bytes
        bInterval              10
can't get debug descriptor: Resource temporarily unavailable
Device Status:     0x0000
  (Bus Powered)

>

**Comment by rsm-gh** [comment]
Hello @spikelinux ,

The configuration was missing but there is already an [issue](https://github.com/rsm-gh/akbl/issues/29) concerning this topic. I'm going to close this one and you can ask for support in the other ticket.

rsm~

**Comment by rsm-gh** [comment]
+[Configuration added for the Alienware M17 R4 ](https://github.com/rsm-gh/akbl/commit/89ffbd4231cfebdc889df143756d674ed5fb4fbb)
