### ISSUE TITLE
installation help

### ISSUE THREAD

**Issue by sirstabbybeard** [rsm-gh/akbl#98]
hi i am sure this is a problem i caused by missing a step or something but i can not figure out what is wrong so here i am for some help please.  i have a 2021 dell G15 ryzen edition, running linux mint 20.2. my keyboard is Bus 003 Device 003: ID 187c:0550 Alienware Corporation AW-ELC.  i am also running a dual boot with windows 10 pro.  i only have the windows partition there for one specific program i can not run with WINE.  i do use it to update Dell bios and etc also.  i have been trying to install some sort of program to control my backlight keyboard.  i have tried a few others with no success.  i wanted to try and install AKBL because it seems to be the only one that uses the larger more complex coding needed for my keyboard.  (I think)  

from the command line i ran

: sudo git clone https://github.com/rsm-gh/akbl.git /home/user/gitapps

then i went to that cloned directory and ran

sudo python3 setup

my computer spit out 
"             
  File "setup", line 22
    if [ "$EUID" -ne 0 ]
                     ^
SyntaxError: invalid syntax

"

what am i doing wrong.

the setup file is set to be executable i have installed all necessary dependencies.  i tried to run it from a file manager. nothing.  i went and downloaded the zip file from the link in the description, extracted it to a different directory, tried to execute the file still gives the same syntax error.  

idk i am sure it is some step i have missed or something but i am lost.  
i have also tried to install and run  erlkonig / alienfx .  but i was unable to detect the keyboard layout because i believe my keyboard is too new and uses the more complex longer scripts.  again i am not sure if it is something i am missing.  i did make sure to delete all of the alienfx files i could find before trying to install AKBL.  i am not a noob and can usually figure out how to fix most problems with my computers by reading and trial and error, but i am stumped on this one.  i am hopeing it is a simple thing i am missing but if not maybe i will get lucky and someone out there can help.

thanks in advance

**Comment by rsm-gh** [comment]
Hello @ sirstabbybeard,

I'm not sure that AKBL will work with your G15 (I don't remember that model), but anyways if you want to install it and try to see if we can support it, for installing the software you must execute the launch file as `./setup` because it is a `.sh` file and not  a python file. And before executing the file, you need to change its execution permission `chmod a+x setup`.


Good luck,
rsm

**Comment by rsm-gh** [comment]
Doc for adding the G15 into AKBL: https://github.com/rsm-gh/akbl#if-my-computer-is-not-supported-what-can-i-do
